name: Build and Deploy Microservices to Azure

on:
  pull_request:
    branches:
      - main  # O cámbialo si usas otra rama como 'production'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push users-api
        run: |
          docker build -t $REGISTRY/users-api ./users-api
          docker push $REGISTRY/users-api

      - name: Build and push auth-api
        run: |
          docker build -t $REGISTRY/auth-api ./auth-api
          docker push $REGISTRY/auth-api

      - name: Build and push reports-api
        run: |
          docker build -t $REGISTRY/reports-api ./reports-api
          docker push $REGISTRY/reports-api

      - name: Deploy to Azure Web App (users-api)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_USERS }}
          images: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/users-api

      - name: Deploy to Azure Web App (auth-api)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_AUTH }}
          images: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/auth-api

      - name: Deploy to Azure Web App (reports-api)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_REPORTS }}
          images: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/reports-api