name: Deploy to Azure

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push patients-service
        run: |
          docker build -t $ACR_LOGIN_SERVER/patients-symptom-service:latest ./services/patients-service
          docker push $ACR_LOGIN_SERVER/patients-symptom-service:latest

      - name: Build and push symptoms-service
        run: |
          docker build -t $ACR_LOGIN_SERVER/symptoms-logging-service:latest ./services/symptoms-service
          docker push $ACR_LOGIN_SERVER/symptoms-logging-service:latest

      - name: Build and push Vue client
        run: |
          docker build -t $ACR_LOGIN_SERVER/vue-symptom-client-app:latest ./client
          docker push $ACR_LOGIN_SERVER/vue-symptom-client-app:latest

      - name: Deploy patients-service to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_SERVICE_PATIENTS_NAME }}
          images: ${{ secrets.ACR_LOGIN_SERVER }}/patients-symptom-service:latest

      - name: Deploy symptoms-service to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_SERVICE_SYMPTOMS_NAME }}
          images: ${{ secrets.ACR_LOGIN_SERVER }}/symptoms-logging-service:latest

      - name: Deploy Vue client to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_SERVICE_CLIENT_NAME }}
          images: ${{ secrets.ACR_LOGIN_SERVER }}/vue-symptom-client-app:latest